services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fluxflicksdb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
